name: solution_app
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  kartal: ^2.3.1
  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.2.4
  animated_bottom_navigation_bar: ^0.3.2
  google_maps_flutter: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.8


flutter:

  uses-material-design: true
  assets:
    - assets/images/


